--liquibase sql formatted

--changes danil:001-init-sql.sql

CREATE TABLE app_user(
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(500) NOT NULL,
    notify_new_events BOOLEAN NOT NULL,
    notify_upcoming BOOLEAN NOT NULL,
    notify_before_hours INT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE event(
    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description VARCHAR(255),
    date_time TIMESTAMPTZ NOT NULL,
    total_tickets INTEGER NOT NULL,
    available_tickets INTEGER NOT NULL,
    cover_url VARCHAR(255),
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE booking(
    booking_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    user_id BIGINT NOT NULL,
    event_id BIGINT NOT NULL,
    ticket_count INTEGER NOT NULL,
    created_at TIMESTAMPTZ NOT NULL,
    expiry_time TIMESTAMPTZ NOT NULL,
    reminder_at TIMESTAMPTZ,
    reminder_sent boolean NOT NULL,
    confirmed BOOLEAN NOT NULL,

    CONSTRAINT fk_booking_user
        FOREIGN KEY (user_id)
        REFERENCES app_user(user_id)
        ON DELETE CASCADE,

    CONSTRAINT fk_booking_event
            FOREIGN KEY (event_id)
            REFERENCES event(event_id)
            ON DELETE CASCADE
);

CREATE TABLE user_roles(
    user_id BIGINT NOT NULL,
    role VARCHAR(255) NOT NULL,

    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES app_user(user_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_user_email ON app_user(email);
CREATE INDEX idx_booking_user_id ON booking(user_id);
CREATE INDEX idx_booking_event_id ON booking(event_id);
CREATE INDEX idx_event_date_time ON event(date_time);

CREATE INDEX idx_booking_pending_reminders
ON booking(reminder_sent, reminder_at)
WHERE reminder_sent = false AND reminder_at IS NOT NULL;
